### ISSUE TITLE
Remove "Edit in Chart Studio" button at each Plotly graph

### ISSUE THREAD

**Issue by TomTheBear** [ClusterCockpit/ClusterCockpit#13]
The button "Edit in Chart Studio" is shown for each plot. This uploads all graph data to the Plotly cloud and is probably a no-go for data security even if the username etc. are not transferred.

According to https://github.com/plotly/documentation/issues/189 :
{modeBarButtonsToRemove: ['sendDataToCloud']}

**Comment by moebiusband73** [comment]
Plotly was dropped and replaced by uplot
