### ISSUE TITLE
Security review SQL queries

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/ClusterCockpit#18]
Review all queries for string concatenation.

Query parameters should be either using prepared statements or quoted arguments.

**Comment by iamlouk** [comment]
The only remaining query with user input that is not using the doctrine query builder is the one for `userStats`. It can only be reached from the GraphQL-API and there the query validator makes sure that the inputs are timestamps. As far as i can tell, there are no SQL-Injection attacks or the like possible anymore.
