### ISSUE TITLE
Needed dependencies in require-dev

### ISSUE THREAD

**Issue by hahnjo** [ClusterCockpit/ClusterCockpit#25]
At least the following two packets are listed in `require-dev`:
 * `symfony/dotenv`
 * `doctrine/doctrine-fixtures-bundle`

Usually production environments of projects with `composer` are setup using `composer install --no-dev`, so these packages will be missing. However, they are apparently needed to setup and initialize the project.

**Comment by moebiusband73** [comment]
You should not use those in production.

The intended use in production is to setup the environement for example from within your apache configuration. I am sorry that I did not yet put documentation for production use online. But my time is scarce.

**Comment by moebiusband73** [comment]
doctrine:fixtures are not used anymore.

dotenv should not be used in the prod environment. It is best practice to set security relevant stuff as passwords in your shell environment. Symfony recommends to set it from your Apache configuration.
