### ISSUE TITLE
Some links don't work when installing into subdirectory

### ISSUE THREAD

**Issue by hahnjo** [ClusterCockpit/ClusterCockpit#27]
Most links work (in particular the top navigation bar), but for example the side navigation in the "Config Panel" don't: They assume that ClusterCockpit is installed at the root of the domain.

**Comment by moebiusband73** [comment]
Does this happen if using the internal PHP web server?

If using in a Apache environement I recommend to use a virtual host configuration.

**Comment by moebiusband73** [comment]
As far as I know Symfony should always be run in a virtual environment.

I tried with an alias to the public web directory but the paths are still present. I am not sure if fixing this with rewrites is a good solution. Why all this effort if with a virtual host a good and secure option is available?
