### ISSUE TITLE
$composer install   met the err

### ISSUE THREAD

**Issue by Roger-Yue** [ClusterCockpit/ClusterCockpit#30]
OS is centos7.6 
Mysql & php72 with needed extension & Composer are  correctly installed.
But i met this sitution:

cockpit$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In DriverManager.php line 269:
!!                                
!!    Malformed parameter "url".  
!!                                
!!  
!!  
Script @auto-scripts was called via post-install-cmd

**Comment by Roger-Yue** [comment]
Let me add some info about os and dependencies.  
(English is not my native language; please excuse typing errors.)

# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

# mysql -V
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

# composer -V
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer version 1.9.0 2019-08-02 20:55:32
# php -v
PHP 7.2.22 (cli) (built: Aug 28 2019 09:29:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

# symfony -V
WARNING The current directory seems configured for as a SymfonyCloud project, but it is not linked yet.
        You can link this directory to an existing project: symfony link [project-id] (get project IDs via symfony projects)
Symfony CLI version v4.6.4 (Tue Aug 13 22:14:53 CST 2019)

after i # su - cockpit and modified .env which i'am sure it can access the db.
met the above situation

**Comment by moebiusband73** [comment]
Hi,

this is an error in the Doctrine ORM. It says that the URL is malformed.
In .env it should be something like:
DATABASE_URL=mysql://<dbuser>:<dbpaswd>@127.0.0.1:3306/<DBname>

Can you check if your URL probably has an error.
Jan

**Comment by Roger-Yue** [comment]
Hello，author

Thanks a lot for u reply! 
I have modified .env and test again:

[cockpit@ClusterCockpit ClusterCockpit]$ mysql -u cockpit -p
Enter password: 
...
MariaDB [(none)]> show databases;
+----------------------+
| Database                   |
+----------------------+
| information_schema |
| ClusterCockpit          |
+----------------------+
MariaDB [(none)]> use ClusterCockpit;
MariaDB [ClusterCockpit]> show tables;
+--------------------------+
| Tables_in_ClusterCockpit |
+--------------------------+
| api_key                            |
| cluster                             |
| configuration                  |
| data                                 |
| job                                   |
| job_job_tag                     |
| job_tag                            |
| jobs_nodes                      |
| metric                              |
| metric_list                        |
| node                                |
| table_sort_config             |
+--------------------------+
**But i met this err that no valid information was available on internet. I'd like to ask you for some advice.**

[cockpit@ClusterCockpit ClusterCockpit]$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package symfony/webpack-encore-pack is abandoned, you should avoid using it. Use symfony/webpack-encore-bundle instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!                                                                                  
!!   [WARNING] Some commands could not be registered:                               
!!                                                                                  
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  
!!                                                                                  
!!   [WARNING] Some commands could not be registered:                               
!!                                                                                  
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  In Client.php line 278:
!!                                     
!!    Notice: Undefined index: scheme  
!!                                     
!!  
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In FileLoader.php line 166:
!!                                                                                 
!!    Class could not be determined for Controller identified by "App\Controller\  
!!    API\UsersController" in App\Controller\API\UsersController (which is being   
!!    imported from "/home/cockpit/ClusterCockpit/config/routes.yaml"). Make sure  
!!     there is a loader supporting the "rest" type.                               
!!                                                                                 
!!  
!!  In RestRouteLoader.php line 153:
!!                                                                                 
!!    Class could not be determined for Controller identified by "App\Controller\  
!!    API\UsersController".                                                        
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-install-cmd

**Comment by Roger-Yue** [comment]
And here is details how i installed.

# yum install epel-release yum-utils -y
# yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
# yum-config-manager --enable remi-php72
# yum update
# yum install php72 -y
# yum install php72-php-fpm php72-php-gd php72-php-json php72-php-mbstring php72-php-mysqlnd php72-php-xml php72-php-xmlrpc php72-php-opcache php-ldap -y
# systemctl enable php72-php-fpm.service
# vim /etc/opt/remi/php72/php.ini

  memory_limit = 1G

# systemctl start php72-php-fpm.service
# yum install composer -y
# yum -y install unzip
# useradd cockpit
# wget -i -c  https://repo.mysql.com//mysql80-community-release-el7-1.noarch.rpm
# yum -y install mysql80-community-release-el7-1.noarch.rpm
# yum -y install mysql-community-server
# systemctl enable --now mysqld
# grep "password" /var/log/mysqld.log          
# mysql -u root  -p

$mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'mypass';
$mysql> CREATE USER cockpit@localhost IDENTIFIED BY 'mypass';
$mysql> CREATE DATABASE ClusterCockpit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
$mysql> GRANT ALL PRIVILEGES ON ClusterCockpit.* TO cockpit@localhost;
$mysql> quit
# su - cockpit
$ git clone https://github.com/ClusterCockpit/ClusterCockpit.git ClusterCockpit
$ cd ClusterCockpit/
$ cp .env.dist .env
$ vim .env
... ...
$ composer install

**Comment by moebiusband73** [comment]
We recommend to use the https://github.com/ClusterCockpit/cc-docker docker compose setup for demo and development.
