### ISSUE TITLE
On which Linux distro has ClusterCockpit been tested?

### ISSUE THREAD

**Issue by weijianwen** [ClusterCockpit/ClusterCockpit#32]
Hi,

I plan to deploy ClusterCockpit for our campus' supercomputer. May I known on whichi Linux distro (and version number) has ClusterCockpit been deployed and tested? Or do you have a plan to distribute ClusterCockpit as a container image?

Thank you.

Jianwen

**Comment by moebiusband73** [comment]
Dear Jianwen,

sorry for the late answer.
ClusterCockpit was tested on Ubuntu 18.04, ArchLinux and MacOS Mojave and Catalina (with homebrew) as well as OpenBSD 6.5  but should run on any system with a recent PHP environment. Out production monitoring system runs Ubuntu 18.04. Please note that there is no stable  release for ClusterCockpit, yet.  We do not plan, at least currently, to distribute a container image.

Jan
