### ISSUE TITLE
Failed to `composer install` due to Script cache:clear returned with error code 1

### ISSUE THREAD

**Issue by weijianwen** [ClusterCockpit/ClusterCockpit#37]
We tried to install ClusterCockpit on our CentOS 7.7 cluster. Error message `Script cache:clear returned with error code 1` was encountered during `composer install`. Shall I proceed to install or check other log?  We confirmed that database scheme is correct and DB access is OK.

Steps to reproduce this issue
------------------------------

1. Install PHP 7.3 and dependent libraries.
2. Install composer.
2. Instal MySQL community edition 8 and initialize the DB.
3. Clone CluserCockpit and edit `.env`.
4. Run `composer install` resulting the following issues.

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!
!!   [WARNING] Some commands could not be registered:
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!                                                                                                                                                                  [12/1864]
!!
!!
!!   [WARNING] Some commands could not be registered:
!!
!!
!!
!!   // Clearing the cache for the development environment with debug
!!   // true
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!
!!  In FileLoader.php line 180:
!!
!!    Notice: Undefined index: scheme in App\Controller\API\JobListController (wh
!!    ich is being imported from "/home/cockpit/ClusterCockpit/config/routes.yaml
!!    "). Make sure there is a loader supporting the "rest" type.
!!
!!
!!  In Client.php line 278:
!!
!!    Notice: Undefined index: scheme
!!
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV]
 [--no-debug] [--] <command>
!!
!!
Script @auto-scripts was called via post-install-cmd
```

Database URL
---------------

The database can be reached via `mysql -ucockpit -D ClusterCockpit -p` .

```
$ grep DATABASE_URL .env
DATABASE_URL=mysql://cockpit:xxxx_xxx@127.0.0.1:3306/ClusterCockpit
```

**Comment by moebiusband73** [comment]
Hi,
sorry for the late reply. I will try to reproduce. I have no centos system available. Lets see.
Best Regards, Jan

**Comment by ErikP94** [comment]
Moin! 

I hope it's not too late:
We faced a similar problem.
Did you locate line 278 in `Client.php`?
Our problem was located in `        $schemeInfo = explode('+', $connParams['scheme']);` in the
`./vendor/influxdb/influxdb-php/src/InfluxDB/Client.php`.
Did you provide an INFLUX_URL in your .env? That solves the problem for us.

Cheers,
Erik

**Comment by moebiusband73** [comment]
In production mode the .env file is not sourced. The common way is to set the required URL for SQL and InfluxDB in your environment, e.g. from your shell if interactive or as part of your apache vhost file.

**Comment by moebiusband73** [comment]
We recommend to use the https://github.com/ClusterCockpit/cc-docker  docker compose setup for demo and development.
