### ISSUE TITLE
Program Detection and Automatic Recommendations

### ISSUE THREAD

**Issue by robertschade** [ClusterCockpit/ClusterCockpit#38]
Hi,
we have recently extended ClusterCockpit to include functionality to automatically evaluate recommendations for jobs based on rules. The recommendations are then written into the working directory of a job, tagged in ClusterCockpit and shown in the job overview page:
![image](https://user-images.githubusercontent.com/46203934/83426835-10796c80-a430-11ea-886a-da74ba61559c.png)

We have also added a function to detect which program is used in a job based on heuristics and hashes. They are automatically tagged in ClusterCockpit and can for example be used to create program-specific statistics for certain metrics. 

Our changes can be found in https://github.com/pc2/ClusterCockpit. They are not yet at the stage of a proper pull request but might be interesting nevertheless. We have also added our local collectors, spank-plugins, and other relevant things in the contrib-subdirectory of the repository.
The system is currently in closed beta on the Noctua cluster in Paderborn and we are actively extending it.
Best Wishes
Robert Schade

**Comment by moebiusband73** [comment]
Hi Robert,

that looks very promising! I will have a look at this development.

Currently the ClusterCockpit development was on hold on my side for the past months.
I will start working again on it, soon. I have a bunch of ideas how it can be easier to
install, maintain and use.

Jan
