### ISSUE TITLE
Configure MetricDataRepository handler via Symfony Autowiring

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/ClusterCockpit#67]
Currently the MetricDataRepository Interface is set hardcoded in the JobData Service.

Only use the Interface in Services and configure which class to use using Symfony Autowiring.
Ideally this should be configured with an Environment Variable.

**Comment by iamlouk** [comment]
I followed [this](https://symfony.com/doc/current/service_container/autowiring.html) guide and used an "alias". Setting the implementation to use for the `MetricDataRepository` interface directly works fine, but the `%env(...)%` syntax does not work here, so I did not manage to use environment variables.

The alias definition can be found in `config/services.yaml` line 32.

**Comment by moebiusband73** [comment]
For now the user has to patch the config file to switch the MetricDataRepository Handler
